#!/usr/bin python3
# title           :exercise 18
# description     :Exercises from https://www.practicepython.org
# author          :Gabriel Ionescu
# date            :2020/03/18
# version         :1.0
# notes           :
# python_version  :3.7.5
# ==============================================================================

"""
Exercise 18:
Create a program that will play the “cows and bulls” game with the user.
The game works like this:
    Randomly generate a 4-digit number.
    Ask the user to guess a 4-digit number.
    For every digit that the user guessed correctly in the correct place,
        they have a “cow”.
    For every digit the user guessed correctly in the wrong place is a “bull”.
    Every time the user makes a guess, tell them how many “cows” and “bulls”
        they have.
    Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout the game and
tell the user at the end.

Say the number generated by the computer is 1038.
An example interaction could look like this:
    Welcome to the Cows and Bulls Game! 
    Enter a number: 
    >>> 1234
    2 cows, 0 bulls
    >>> 1256
    1 cow, 1 bull
    ...
Until the user guesses the number.
"""

import random


def check(n, g):
    """
    Checks if correct guess or how many cows/bulls
    Resets cows/bulls on every check
    """
    cows = 0
    bulls = 0

    # change numbers into list to be easier to work with
    n = list(str(n))
    g = list(str(g))
    for i in range(len(g)):
        if g[i] in n:
            if g[i] == n[i]:
                cows += 1
                n[i] = 11       # change values to ignore when couting bulls
                g[i] = 11       # change values to ignore when couting bulls
    for i in g:
        if int(i) <= 9:         # if value was not counted as cow
            if i in n:
                bulls += 1
                # change value to ignore when couting next bulls
                n[n.index(i)] = 11

    # check if 1 or many cows/bulls
    if cows == 1:
        c = 'cow'
    else:
        c = 'cows'
    if bulls == 1:
        b = 'bull'
    else:
        b = 'bulls'
    print('{} {}, {} {}'.format(cows, c, bulls, b))


def play(n):
    tries = 0
    while True:
        tries += 1
        while True:
            try:
                guess = int(input('Please enter a 4 digits number >>> '))
                if len(str(guess)) == 4:
                    break
            except:
                pass
        if guess == n:
            print('-----')
            print('Congratulations !!!')
            print('You guess the number in {} tries.'.format(tries))
            break
        else:
            check(n, guess)


if __name__ == '__main__':
    print('\n=====')
    print('Welcome to the Cows and Bulls Game!')
    print('Enter a number:')

    number = random.randint(1000, 9999)
    play(number)

    print('=====\n')
